#theme = "/home/doanac/.config/sway/solarized-dark.toml"
#icons = "/home/doanac/.config/sway/awesome5.toml"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 5
# format = "{barchart} {utilization} {frequency}"
format = "{utilization} {frequency}"

[[block]]
block = "load"
interval = 5
format = "{1m}"

#[[block]]
#block = "sound"

[[block]]
block = "networkmanager"
on_click = "terminator --title NetworkManager -x nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^10} {strength}"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 5
format = "%R"

[[block]]
icons_format = ""
block = "time"
interval = 5
format = "%m-%d %r"
timezone = "US/Central"
